# Generated by Django 4.2.28 on 2026-03-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_post',
            field=models.TextField(default='en attente'),
            preserve_default=False,
        ),
    ]
