# Generated by Django 4.2.23 on 2026-02-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internaute', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internaute',
            name='abonne',
            field=models.BooleanField(default=False),
        ),
    ]
