# Generated by Django 4.2.28 on 2026-07-12 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internaute', '0002_alter_internaute_abonne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internaute',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
