# Generated by Django 4.2.28 on 2026-07-12 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0003_post_content_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('harmfull', models.BooleanField(default=False)),
                ('nb_like_com', models.IntegerField(default=0)),
                ('nb_dislike_com', models.IntegerField(default=0)),
                ('internaute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='post.post')),
            ],
        ),
        migrations.CreateModel(
            name='Liker_com',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_com', to='comment.comment')),
                ('internaute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_com', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('internaute', 'comment')},
            },
        ),
    ]
