# Generated by Django 4.2.28 on 2026-05-22 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0002_add_live_url_to_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='live_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='profile',
        ),
    ]
